Importe the lib

In [4]:
import numpy as np

Create 2 list

In [5]:
list1 = [1,2,3,4]
list2 = [11,22,33,44]
array1 = np.array(list1)
array1

array([1, 2, 3, 4])

Make a list of lists

In [6]:
lists = [list1,list2]

Make multi-dimensional array

In [7]:
array2 = np.array(lists)
array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

Print size of the array

In [8]:
array2.shape

(2, 4)

Print data type of the array

In [10]:
array2.dtype

dtype('int32')

# special case arrays

In [19]:
#Zeros array
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [20]:
#Ones 2-dim array
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [21]:
#empty array
np.empty(5)
np.empty((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [26]:
#Identity array
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [27]:
#Range array
np.arange(5)

array([0, 1, 2, 3, 4])