In [10]:
import numpy as np

In [20]:
array1 = np.arange(0,11)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Get values from 1 to 5

In [21]:
array1[1:5]

array([1, 2, 3, 4])

Set value with index range (Broadcasting)

In [22]:
array1[0:5]=100
array1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Reset the array

In [23]:
array1 = np.arange(0,11)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
array_slice = arr[0:6]
array_slice

array([99, 99, 99, 99, 99, 99])

Change the Slice


In [25]:
array_slice[:]=99
array_slice


array([99, 99, 99, 99, 99, 99])

In [26]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Copy the array

In [28]:
array1_copy = array1.copy()
array1_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Index 2D array

In [30]:
array_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
#row
array_2d[1]

array([20, 25, 30])

In [35]:
#element
array_2d[1][0]

20

In [37]:
#Shape (2,2) from top right corner
array_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [42]:
#Shape bottom row
array_2d[2]

#Or
array_2d[2,:]

array([35, 40, 45])

Print length

In [44]:
length = array_2d.shape[1]
length

3