In [2]:
import numpy as np

In [4]:
from __future__ import division

In [5]:
array1 = np.array([[1,2,3],[8,9,10]])
array1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

Multiply

In [9]:
array1*array1

array([[  1,   4,   9],
       [ 64,  81, 100]])

Subtract

In [10]:
array1-array1

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
1 / array1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

الاس

In [15]:
array1**3

array([[   1,    8,   27],
       [ 512,  729, 1000]], dtype=int32)